import 'package:get/get.dart';

class Translator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'مقالات': 'doc',
          'بازدید کنندگان': 'Viewers',
          'Beta version.If you exprience any problem or having a suggestion please tell us.':'Beta version.If you exprience any problem or having a suggestion please tell us.',
          'English': "فارسی",
          'ModSec Admin Panel': 'ModSec Admin Panel',
          'Dashboard': 'Dashboard',
          'CPU Usage': 'CPU Usage',
          'Cloud Usage': 'Cloud Usage',
          'Memory Usage': 'Memory Usage',
          'Traffic Usage': 'Traffic Usage',
          'Attacks per Application': 'Attacks per Application',
          'Welcome Admin!': 'Welcome Admin!',
          'Time remaining:': 'Time remaining:',
          'admin1': 'admin1',
          'Error': 'Error',
          'Please fill the inputs correctly!': 'Please fill the inputs correctly!',
          'Login Successful!': 'Login Successful!',
          'Welcome dear test.': 'Welcome dear test.',
          'Invalid username or password': 'Invalid username or password',
          'Check your internet connection !': 'Check your internet connection!',
          'Logout': 'Logout',
          'Are you sure you want to logout?': 'Are you sure you want to logout?',
          'Cancel': 'Cancel',
          'Confirm': 'Confirm',
          'Profile': 'Profile',
          'Settings': 'Settings',
          'Idle Alert': 'Idle Alert',
          'You have been idle for some min. Do you want to stay?': 'You have been idle for some min. Do you want to stay?',
          'YES': 'YES',
          'Websites': 'Websites',
          'Statistics': 'Statistics',
          'System Log': 'System Log',
          'Dark Mode': 'Dark Mode',
          'Language': 'Language',
          'Login': 'Login',
          'Welcome to WAF2Flutter!': 'Welcome to WAF2Flutter!',
          'Username': 'Username',
          'Password': 'Password',
          'Demo Login method using pre defined username and pass': 'Demo Login method using pre defined username and pass',
          'Status': 'Status',
          'Visitors: ': 'Visitors: ',
          'Last refresh: ': 'Last refresh: ',
          'Suspected: ': 'Suspected: ',
          'Critical: ': 'Critical: ',
          'Safe': 'Safe',
          'WAF is ON!': 'WAF is ON!',
          'وب سایت ها': 'Websites',
          'زمان باقی مانده:   ':'Time remaining:   '
        },
        'fa': {
          'doc': 'مقالات',
          'Viewers': 'بازدید کنندگان',
          'Time remaining:   ': "زمان باقی مانده:    ",
          'Beta version.If you exprience any problem or having a suggestion please tell us.': 'نسخه ازمایشی.با در اختیار گذاشتن خطا ها باگ ها و یا پیشنهاداتنون ما را در مسیر ساخت تجربه ایی بهتر یاری کنید! با تشکر',
          'فارسی': 'English',
          'ModSec Admin Panel': 'پنل ادمین ModSec',
          'Dashboard': 'داشبورد',
          'CPU Usage': 'مصرف CPU',
          'Cloud Usage': 'مصرف ابر',
          'Memory Usage': 'مصرف حافظه',
          'Traffic Usage': 'مصرف ترافیک',
          'Attacks per Application': 'حملات به ازای برنامه',
          'Welcome Admin!': 'خوش آمدید ادمین!',
          'Time remaining:': 'زمان باقی مانده:',
          'admin1': 'ادمین1',
          'Error': 'خطا',
          'Please fill the inputs correctly!': 'لطفا ورودی ها را به درستی پر کنید!',
          'Login Successful!': 'ورود موفقیت آمیز!',
          'Welcome dear test.': 'خوش آمدید تست عزیز.',
          'Invalid username or password': 'نام کاربری یا رمز عبور نامعتبر است',
          'Check your internet connection !': 'اتصال اینترنت خود را بررسی کنید!',
          'Logout': 'خروج',
          'Are you sure you want to logout?': 'آیا مطمئنید که می‌خواهید خارج شوید؟',
          'Cancel': 'لغو',
          'Confirm': 'تایید',
          'Profile': 'پروفایل',
          'Settings': 'تنظیمات',
          'Idle Alert': 'هشدار عدم فعالیت',
          'You have been idle for some min. Do you want to stay?': 'برای چند دقیقه بیکار بوده‌اید. آیا می‌خواهید بمانید؟',
          'YES': 'بله',
          'Statistics': 'آمار',
          'System Log': 'لاگ سیستم',
          'Dark Mode': 'حالت تاریک',
          'Language': 'زبان',
          'Login': 'ورود',
          'Welcome to WAF2Flutter!': 'خوش آمدید به WAF2Flutter!',
          'Username': 'نام کاربری',
          'Password': 'رمز عبور',
          'Demo Login method using pre defined username and pass': 'روش ورود آزمایشی با استفاده از نام کاربری و رمز عبور از پیش تعیین شده',
          'Status': 'وضعیت',
          'Visitors: ': 'بازدیدکنندگان: ',
          'Last refresh: ': 'آخرین بروزرسانی: ',
          'Suspected: ': 'مشکوک: ',
          'Critical: ': 'بحرانی: ',
          'Safe': 'ایمن',
          'WAF is ON!': 'WAF فعال است!',
          'Websites': 'وب سایت ها'
        },
      };
}
